### ISSUE TITLE
MUTE the MAIN

### ISSUE THREAD

**Issue by bobby909090** [Jille/rcf-m18#2]
Hi, sorry for the stupid question but I just can't get the system to work. To MUTE the MAIN which OSC frame should be sent?
I sent:
/00/00/mt_000
but I don't understand how the rest of the message should be composed.

Any help is really appreciated!

Thanks
Lorenzo

**Comment by Jille** [comment]
Does https://github.com/Jille/rcf-m18/blob/master/rcfm18/generated.go#L4350 help?

**Comment by bobby909090** [comment]
Hi, thanks for reply!
I saw this part of the code but I don't understand what the exact UDP frame is that is being sent (including the bool parameter).
If you can give me an example that would be great.

Thanks
Lorenzo

**Comment by Jille** [comment]
https://go.dev/play/p/ET92hRfBQzJ

**Comment by bobby909090** [comment]
Thanks, problem solved.
